# Generated by Django 5.1.2 on 2024-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
