# Generated by Django 5.1.2 on 2024-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_trainee_comments_alter_trainee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
